trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

steps:
# Azure Pipelines has a weird bug where running tests from a fresh install
# will cause the following error, which goes away upon running mill again.
# We work around it by running the tests twice (!!!)
# flexpret.test.compileClasspath java.util.NoSuchElementException: key not found: https://oss.sonatype.org/content/repositories/releases/com/lihaoyi/utest_2.12/maven-metadata.xml
- script: |
    # Ubuntu 20.04 only has Verilator 4.028 but we neeed a more modern version
    #sudo apt-get install -y -qq verilator
    wget -q https://github.com/sifive/verilator/releases/download/4.036-0sifive2/verilator_4.036-0sifive2_amd64.deb -O verilator.deb
    sudo dpkg -i verilator.deb
    wget -q https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack/releases/download/v8.3.0-2.3/xpack-riscv-none-embed-gcc-8.3.0-2.3-linux-x64.tar.gz -O riscv.tgz
    tar zxf riscv.tgz
    mv xpack-riscv-none-embed-gcc-8.3.0-2.3 ~/riscv-embed-gcc
    ln -s ~/riscv-embed-gcc/bin/riscv-none-embed-as ~/riscv-embed-gcc/bin/riscv32-unknown-elf-as
    ln -s ~/riscv-embed-gcc/bin/riscv-none-embed-gcc ~/riscv-embed-gcc/bin/riscv32-unknown-elf-gcc
    ln -s ~/riscv-embed-gcc/bin/riscv-none-embed-ld ~/riscv-embed-gcc/bin/riscv32-unknown-elf-ld
    ln -s ~/riscv-embed-gcc/bin/riscv-none-embed-objdump ~/riscv-embed-gcc/bin/riscv32-unknown-elf-objdump
  displayName: Prereqs
- script: |
    ./test/run_tests.sh || true
    ./test/run_tests.sh
  displayName: 'Unit tests'
- script: ./test/basic_build.sh
  displayName: 'Basic build'
- script: (export PATH="$HOME/riscv-embed-gcc/bin:$PATH" && ./test/basic_sim.sh)
  displayName: 'Basic simulation'
