trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

steps:
# Azure Pipelines has a weird bug where running tests from a fresh install
# will cause the following error, which goes away upon running mill again.
# We work around it by running the tests twice (!!!)
# flexpret.test.compileClasspath java.util.NoSuchElementException: key not found: https://oss.sonatype.org/content/repositories/releases/com/lihaoyi/utest_2.12/maven-metadata.xml
- script: |
    ## Install Verilator
    # Ubuntu 20.04 only has Verilator 4.028 but we neeed a more modern version
    # so we do not use 'sudo apt-get install -y -qq verilator' here.
    wget -q https://github.com/sifive/verilator/releases/download/4.036-0sifive2/verilator_4.036-0sifive2_amd64.deb -O verilator.deb
    sudo dpkg -i verilator.deb
    ## Install RISC-V GCC from source
    sudo apt-get install autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev libslirp-dev
    git clone https://github.com/riscv/riscv-gnu-toolchain
    cd riscv-gnu-toolchain
    ./configure --prefix=/opt/riscv
    make
    which riscv64-unknown-elf-gcc
  displayName: Prereqs
- script: sbt 'test'
  displayName: 'FlexPRET hardware unit tests'
- script: source env.bash && cmake -B build && cd build && make all install
  displayName: 'Generate verilog, emulator and install it to SDK'
- script: |
    # Set environment to find RISC-V compiler
    export RISCV_TOOL_PATH_PREFIX=/opt/riscv
    source env.bash

    # Step into SDK and run tests
    cd sdk && cmake -B build && cd build && make && ctest
  displayName: 'Run C tests'
  
  # We did not run the two first as part of the script to make it easier to
  # debug issues with the job
- script: |
    # Set environment to find RISC-V compiler
    export RISCV_TOOL_PATH_PREFIX=/opt/riscv
    source env.bash
    
    # Run multiple tests with script
    ./scripts/run_multiple_tests.sh
  displayName: 'Multiple C tests'
