#!/bin/bash

# Check if exactly one argument is provided
if [ $# -ne 1 ]; then
  echo "Usage: $0 [ispm]"
  exit 1
fi

# Get the directory of the script and the verilator emulation
script_dir = $(dirname "$0")
emu = "$script_dir/fp-verilator"
working_dir = $(pwd)

# Check if the file exists
if [ ! -f "$1" ]; then
  echo "File not found: $1"
  exit 1
fi



# Check if the file exists
if [ ! -f "$emu" ]; then
  echo "Did not find verilator emulator at: $1"
  exit 1
fi

# Get the filename from the path
filename=$(basename "$1")

# Copy the file to the current directory
cp "$1" "$script_dir/ispm.mem"

# Move into the emulator directory
cd $script_dir

# Execute the emulator
$emu

# Remove the copied file
rm ispm.mem

# Go back to start
cd $working_dir




