# The following method is used to generate .tcl files from make
# See https://stackoverflow.com/questions/649246/is-it-possible-to-create-a-multi-line-string-variable-in-a-makefile

include $(FLEXPRET_ROOT_DIR)/hwconfig.mk
CLK_PERIOD_NS := $(shell echo $$((1000 / $(CLK_FREQ_MHZ))))
CLK_HALF_PERIOD_NS := $(shell echo $$(($(CLK_PERIOD_NS) / 2)))

$(PROJECT_GENERATED_DIR)/flash_runnable.tcl: $(PROJECT_GENERATED_DIR)/variables.tcl $(PROJECT_GENERATED_DIR)/set_program_file.tcl
	cat $(PROJECT_GENERATED_DIR)/variables.tcl $(BOARD_TCL_DIR)/flash.tcl > $@

# Not really dependent on clk_wiz_config, but easier to force it to generate
$(PROJECT_GENERATED_DIR)/bitstream_runnable.tcl: $(PROJECT_GENERATED_DIR)/variables.tcl $(PROJECT_DIR)/xdc/constraints.xdc $(PROJECT_GENERATED_DIR)/clk_wiz_config.tcl
	cat $(PROJECT_GENERATED_DIR)/variables.tcl $(BOARD_TCL_DIR)/setup.tcl $(BOARD_TCL_DIR)/bitstream.tcl > $@

$(PROJECT_DIR)/xdc/constraints.xdc: $(PROJECT_DIR)/xdc/clock.xdc
	cat $(PROJECT_DIR)/xdc/*.xdc > $(PROJECT_DIR)/xdc/constraints.xdc

$(PROJECT_GENERATED_DIR)/variables.tcl:
	echo "$$VARIABLES_TCL" > $@

$(PROJECT_GENERATED_DIR)/clk_wiz_config.tcl:
	echo "$$CLK_WIZ_CONFIG_TCL" > $@

$(PROJECT_GENERATED_DIR)/set_program_file.tcl:
	echo "$$SET_PROGRAM_FILE_TCL" > $@

$(PROJECT_DIR)/xdc/clock.xdc:
	echo "$$CLOCK_XDC" > $@

clean::
	rm -rf $(PROJECT_GENERATED_DIR)
	rm -f $(PROJECT_DIR)/xdc/clock.xdc
	rm -f $(PROJECT_DIR)/xdc/constraints.xdc

HASHTAG := \#
define COMMON_WARNING
$(HASHTAG) This file is automatically generated and based on configuration
$(HASHTAG) set elsewhere in the project.
$(HASHTAG) 
$(HASHTAG) Should not be edited.
endef

# variables.tcl
define VARIABLES_TCL
$(COMMON_WARNING)

set outputDir ./vivado
set projectName $(PROJECT_NAME)
set boardName $(BOARD_NAME)
set partShort $(PART_SHORT)
set part $(PART)
set nCores $(NCORES)
endef
export VARIABLES_TCL

# clk_wiz_config.tcl
define CLK_WIZ_CONFIG_TCL
$(COMMON_WARNING)

set_property -dict [list CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {$(CLK_FREQ_MHZ)} CONFIG.MMCM_CLKOUT0_DIVIDE_F {20.000} CONFIG.CLKOUT1_JITTER {151.636}] [get_ips clk_wiz_0]
endef
export CLK_WIZ_CONFIG_TCL

# set_program_file.tcl
define SET_PROGRAM_FILE_TCL
$(COMMON_WARNING)

set_property PROGRAM.FILE {$(PROJECT_DIR)/bitstream.bit} [get_hw_devices $(PART_SHORT)_1]
endef
export SET_PROGRAM_FILE_TCL

# Clock.xdc
define CLOCK_XDC
$(COMMON_WARNING)

$(HASHTAG)$(HASHTAG) $(CLK_FREQ_MHZ) MHz clock
set_property -dict {PACKAGE_PIN Y9 IOSTANDARD LVCMOS33} [get_ports {INPUT_CLOCK}];  # "INPUT_CLOCK"
create_clock -period $(CLK_PERIOD_NS).000 -name sys_clk_pin -waveform {0.000 $(CLK_HALF_PERIOD_NS).000} -add [get_ports INPUT_CLOCK]
endef
export CLOCK_XDC
